# Generated by Django 6.1 on 2026-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
                ('excerpt', models.TextField()),
                ('cover_image', models.ImageField(upload_to='posts')),
                ('content_html', models.TextField()),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects')),
                ('external_url', models.URLField()),
            ],
        ),
    ]
