# Generated by Django 6.1 on 2026-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cover_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
