# Generated by Django 6.1 on 2026-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_excerpt_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(help_text='Enter the final rendered HTML content of the post. Example: <h2>Introduction</h2><p>...</p>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Write a short summary of the post. This text is used as the post preview.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Upload the cover image for the post.', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Enable this to make the post publicly available. Unpublished posts are hidden from the public API.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(help_text='Enter the date when the post should be published. Future dates will not be shown publicly.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatically generated from the title. Leave empty to generate it automatically.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, help_text='Enter the post title. Example: Docker Basics for Developers.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Write a brief description of the project, including its purpose and key features.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_url',
            field=models.URLField(help_text='Enter the external project URL. Example: https://github.com/username/project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Upload an image representing the project.', upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_index=True, help_text='Enter the project title. Example: Portfolio Website.', max_length=150, unique=True),
        ),
    ]
