# Generated by Django 6.1 on 2026-08-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_content_html_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(help_text='Enter the final rendered HTML content of the post. Example: ```txt<h2>Introduction</h2>``````txt<p>...</p>```'),
        ),
    ]
