# Generated by Django 6.1 on 2026-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_url',
            field=models.URLField(help_text='Enter the external project URL. Example: https://www.your-site.com.'),
        ),
    ]
