# Generated by Django 6.1 on 2026-08-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_project_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(help_text='Enter the final rendered HTML content of the post. Example: &lt;h2&gt;Introduction&lt;/h2&gt;&lt;p&gt;Your content here...&lt;/p&gt;'),
        ),
    ]
