# Generated by Django 6.1 on 2026-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(db_index=True, help_text='Enter the company name. Example: Google.', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Describe your responsibilities, achievements, and work. Example: Developed and maintained web applications.'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.CharField(db_index=True, help_text='Enter the employment period. Examples: 2022 - Present, 2020 - 2022.', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(db_index=True, help_text='Enter your job role. Example: Senior Backend Developer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(db_index=True, help_text='Enter the name of the skill. Example: Python, Django, Docker.', max_length=100, unique=True),
        ),
    ]
