# Generated by Django 6.1 on 2026-08-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_experience_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-id']},
        ),
    ]
